### ISSUE TITLE
Missing message header due to missing dependency.

### ISSUE THREAD

**Issue by spuetz** [uos/mesh_tools#11]
See http://docs.ros.org/en/jade/api/catkin/html/howto/format2/cpp_msg_dependencies.html

`fatal error: mesh_msgs/TriangleIndices.h: No such file or directory`

**Comment by thschafer** [comment]
Hi spuetz,
Could you describe exactly how you fixed this issue? I am running into the same problem in the uos/lvr_ros package.
Thanks

**Comment by thschafer** [comment]
seems to be related to this change in mesh_tools:
https://github.com/uos/mesh_tools/commit/c66002aff86e656f470cca0384b42cdba1540661
