### ISSUE TITLE
How to install the project?

### ISSUE THREAD

**Issue by aa-tom** [uos/mesh_tools#12]
Hi. I'm interested in using this package as part of a project and wondering what the easiest method of installing is. Is there a binary I can download, or would I need to build the project from source?

Thanks!

**Comment by spuetz** [comment]
Hi, we are currently release the new version. So the easiest way is to use the official ROS repos -> `sudo apt install ros-melodic-mesh-tools` If you wait another two or three weeks, the new version will be available. Cheers.
