### ISSUE TITLE
Minimal example

### ISSUE THREAD

**Issue by ToniRV** [uos/mesh_tools#2]
It would be great if you could provide a data sample to quickly test your package.
Something similar to what you show in the videos

**Comment by spuetz** [comment]
As we changed the hdml structure, we will provide some datasets after we implemented the new hdml structure here. Will be available soon.

**Comment by HareshMiriyala** [comment]
is it available yet ?

**Comment by mklpiening** [comment]
For an example take a look at our [pluto_robot package](https://github.com/uos/pluto_robot).
