### ISSUE TITLE
Git submodule HighFive

### ISSUE THREAD

**Issue by ToniRV** [uos/mesh_tools#3]
When building the package I did a simple `git clone` but I had the error that `ext/HighFive/include` is empty... I realized it was a submodule and build it manually by cloning HighFive in the desired location. It would be great to at least document how to install this package.
Also do you plan to offer it as an `ros-melodic-mesh-tools` package?

**Comment by spuetz** [comment]
Hi @ToniRV, yes we plan to release this software package for kinetic, lunar, and melodic soon.

**Comment by marcusabate** [comment]
Also struggled with install a bit. One quick note is that having a `.gitmodules` file in the root directory defining the modules so that we can run
```
git submodule init
git submodule update
```
will solve this problem and cause the dependencies to clone in properly. Having the `.gitmodules` in the `/hdf5_map_io` directory caused problems for me.

**Comment by VahidBehtajiSiahkalMahalleh** [comment]
> When building the package I did a simple `git clone` but I had the error that `ext/HighFive/include` is empty... I realized it was a submodule and build it manually by cloning HighFive in the desired location. It would be great to at least document how to install this package.
> Also do you plan to offer it as an `ros-melodic-mesh-tools` package?

**Comment by VahidBehtajiSiahkalMahalleh** [comment]
Hi, I have face same error. Is there any structure  how to build HighFive manually?

**Comment by VahidBehtajiSiahkalMahalleh** [comment]
> Hi, I have face same error. Is there any structure how to build HighFive manually?

I have solved problem by building lvr2.

**Comment by spuetz** [comment]
Just run `git submodule update --init --recursive`
