### ISSUE TITLE
Ros2 and Rviz2 port?

### ISSUE THREAD

**Issue by mikebentley15** [uos/mesh_tools#7]
It seems weird that it is not easy to display a mesh in RViz without an external plugin or hacking a URDF file to do it for you.

Then I found this project that looks like everything I need and more.  Great work here.  Is there any effort in place to get it working in Ros2 with Rviz2?  As I understand, RViz has not changed much in porting to Ros2.

**Comment by mikebentley15** [comment]
https://index.ros.org/doc/ros2/Contributing/Migration-Guide/

**Comment by spuetz** [comment]
Feel free to propose a pull request. Maybe the port to RViz2 will be done in 2021, but maybe the software will be ported not before 2022.

**Comment by mikebentley15** [comment]
For now, I've moved to using the `MESH_RESOURCE` marker type in RViz.  It's good enough for my use case.

I had tried to migrate this code myself, but I don't know enough about ROS1, ROS2, or this code base to do it in a reasonable amount of time.
