### ISSUE TITLE
Resolve conflicts between lvr2 and the mesh tools

### ISSUE THREAD

**Issue by spuetz** [uos/mesh_tools#8]
Selecting previously unselected package ros-melodic-hdf5-map-io.
Preparing to unpack .../35-ros-melodic-hdf5-map-io_1.0.0-2bionic.20200429.182051_amd64.deb ...
Unpacking ros-melodic-hdf5-map-io (1.0.0-2bionic.20200429.182051) ...
dpkg: error processing archive /tmp/apt-dpkg-install-D2PVZ2/35-ros-melodic-hdf5-map-io_1.0.0-2bionic.20200429.182051_amd64.deb (--unpack):
 trying to overwrite '/opt/ros/melodic/include/highfive/H5Attribute.hpp', which is also in package ros-melodic-lvr2 19.12.1-1bionic.20200107.200812

...

Unpacking ros-melodic-mesh-tools (1.0.0-2bionic.20200506.151004) ...
Errors were encountered while processing:
 /tmp/apt-dpkg-install-D2PVZ2/35-ros-melodic-hdf5-map-io_1.0.0-2bionic.20200429.182051_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by mklpiening** [comment]
The HighFive library has been replaced with a lvr2 dependency.
